name: Build HTML Index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create index.html
        run: |
          echo "<!DOCTYPE html>
          <html lang='en'>
          <head>
              <meta charset='UTF-8'>
              <meta name='viewport' content='width=device-width, initial-scale=1.0'>
              <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico">
              <title>zksward - Claude Shares</title>
              <style>
                  :root {
                      --bg: #282828;
                      --bg1: #3c3836;
                      --fg: #ebdbb2;
                      --purple: #d3869b;
                      --blue: #83a598;
                      --gray: #928374;
                      --green:  #98971a;
                  }
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 2rem;
                      line-height: 1.6;
                      background-color: var(--bg);
                      color: var(--fg);
                  }
                  h1 { 
                      color: var(--purple);
                      border-bottom: 2px solid var(--bg1);
                      padding-bottom: 0.5rem;
                  }
                  .file-list {
                      list-style: none;
                      padding: 0;
                  }
                  .file-list li {
                      margin: 0.5rem 0;
                      padding: 0.5rem;
                  }
                  .file-list a {
                      color: var(--blue);
                      text-decoration: none;
                      display: block;
                      font-size: 1.5rem;
                  }
                  .file-list a:hover {
                      color: var(--green);
                  }
                  .last-modified {
                      color: var(--gray);
                      font-size: 0.9rem;
                      display: block;
                      margin-top: 0.25rem;
                  }
                  .last-updated {
                      color: var(--gray);
                      font-size: 0.9rem;
                      margin-top: 2rem;
                      border-top: 2px solid var(--bg1);
                      padding-top: 1rem;
                  }
              </style>
          </head>
          <body>
              <h1>Claude Shares</h1>
              <ul class='file-list'>" > index.html

          # Create a temporary file to store entries
          temp_file=$(mktemp)

          # Find all HTML files and process them
          find . -name "*.html" ! -name "index.html" -type f | while read file; do
              # Remove leading ./ from filepath
              clean_path=${file#./}
              # Extract title (everything before the date)
              title=$(echo "$clean_path" | sed -E 's/^(.*) - Claude \([0-9]{1,2}_[0-9]{1,2}_[0-9]{4}.*\)\.html$/\1/')
              # Extract date and convert to sortable format (YYYY-MM-DD HH:MM:SS)
              date_str=$(echo "$clean_path" | sed -E 's/^.* \(([0-9]{1,2})_([0-9]{1,2})_([0-9]{4}) ([0-9]{1,2})_([0-9]{1,2})_([0-9]{1,2}) (AM|PM)\)\.html$/\3-\1-\2 \4:\5:\6 \7/')
              
              # Format date for display (Month DD, YYYY at HH:MM PM/AM)
              display_date=$(date -d "$(echo "$date_str" | sed 's/AM/am/;s/PM/pm/')" "+%B %d, %Y at %I:%M %p" 2>/dev/null)
              
              # Store in temporary file: sortable_date|display_date|title|clean_path
              echo "$date_str|$display_date|$title|$clean_path" >> "$temp_file"
          done

          # Sort by date (newest first) and create list items
          sort -r -t'|' -k1 "$temp_file" | while IFS='|' read -r sort_date display_date title clean_path; do
              echo "<li><a href='$clean_path'>$title</a> <span class='last-modified'>($display_date)</span></li>" >> index.html
          done

          # Clean up temporary file
          rm "$temp_file"

          echo "</ul>
              <div class='last-updated'>
                  Last updated: $(date '+%Y-%m-%d %H:%M:%S')
              </div>
          </body>
          </html>" >> index.html

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add index.html
          git commit -m "Auto-update index.html"
          git push
